apiVersion: v1
entries:
  seaweedfs-operator:
  - apiVersion: v2
    appVersion: 1.0.4
    created: "2025-07-20T07:19:48.497768195Z"
    description: A Helm chart for the seaweedfs-operator
    digest: 18e0af86db44a807e0d828f17fc35700a9b4ab35c31f9d5d220ad0008185f0ea
    maintainers:
    - name: chrislusf
      url: https://github.com/chrislusf
    name: seaweedfs-operator
    type: application
    urls:
    - https://seaweedfs.github.io/seaweedfs-operator/helm/seaweedfs-operator-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: 1.0.2
    created: "2025-03-27T15:34:03.394564646Z"
    description: A Helm chart for the seaweedfs-operator
    digest: 9cd2079997c28efd73a220782047bf46589e762b1d7a7af9beb92d4e5e4919ad
    maintainers:
    - name: chrislusf
      url: https://github.com/chrislusf
    name: seaweedfs-operator
    type: application
    urls:
    - https://seaweedfs.github.io/seaweedfs-operator/helm/seaweedfs-operator-0.1.0.tgz
    version: 0.1.0
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2024-10-17T16:46:34.202841886Z"
    description: A Helm chart for the seaweedfs-operator
    digest: b4344ef75dc3545aaf74872d5759e97e2e9b0b068d2aadf2a5d7a13eaa70198f
    maintainers:
    - name: chrislusf
      url: https://github.com/chrislusf
    name: seaweedfs-operator
    type: application
    urls:
    - https://seaweedfs.github.io/seaweedfs-operator/helm/seaweedfs-operator-0.0.2.tgz
    version: 0.0.2
generated: "2025-07-20T07:19:48.495776931Z"
